# Generated by Django 5.0.6 on 2024-08-28 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0002_messagemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.TextField()),
                ('phone_no', models.CharField(max_length=10)),
                ('uemail', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('category', models.TextField()),
                ('menu', models.TextField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
                ('country', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('total', models.TextField()),
                ('payment', models.TextField()),
            ],
        ),
    ]
