# Generated by Django 5.0.6 on 2024-08-28 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0003_ordermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='phone_no',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='pincode',
            field=models.PositiveIntegerField(),
        ),
    ]
