# Generated by Django 5.0.6 on 2024-09-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0004_alter_ordermodel_phone_no_alter_ordermodel_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='quantity',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='size',
            field=models.TextField(null=True),
        ),
    ]
