# Generated by Django 5.0.6 on 2024-09-02 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0005_ordermodel_quantity_ordermodel_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='userModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('user_img', models.ImageField(upload_to='folder')),
                ('user_email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
