# Generated by Django 5.0.6 on 2024-09-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0006_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_img',
            field=models.ImageField(null=True, upload_to='folder'),
        ),
    ]
