# Generated by Django 5.0.6 on 2024-09-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0007_alter_usermodel_user_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phone_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
