# Generated by Django 5.0.6 on 2024-09-08 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0008_usermodel_address_usermodel_dob_usermodel_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='address',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='phone_no',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='user_img',
        ),
    ]
