# Generated by Django 5.0.6 on 2024-09-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0010_alter_usermodel_password_alter_usermodel_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='country',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='phonno',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
