# Generated by Django 5.0.6 on 2024-09-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0012_rename_country_usermodel_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermodel',
            old_name='dog',
            new_name='dor',
        ),
    ]
