# Generated by Django 5.0.6 on 2024-09-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0016_productmodel_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='category',
        ),
    ]
