# Generated by Django 5.0.6 on 2024-09-11 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0017_remove_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coffeine.categorymodel'),
        ),
    ]
