# Generated by Django 5.0.6 on 2024-09-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0019_rename_item_name_categorymodel_pro_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymodel',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
