# Generated by Django 5.0.6 on 2024-09-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0020_categorymodel_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categorymodel',
            old_name='category',
            new_name='cat_name',
        ),
    ]
