# Generated by Django 5.0.6 on 2024-09-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0022_alter_productmodel_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='post',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_img',
            field=models.ImageField(null=True, upload_to='folder'),
        ),
    ]
