# Generated by Django 5.0.6 on 2024-09-13 06:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0023_usermodel_post_usermodel_user_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddtoCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('status', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coffeine.productmodel')),
            ],
        ),
    ]
