# Generated by Django 5.0.6 on 2024-09-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0026_remove_ordermodel_country_remove_ordermodel_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Coffeine.usermodel'),
        ),
    ]
