# Generated by Django 5.0.6 on 2024-09-17 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0028_rename_user_ordermodel_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='user_email',
        ),
    ]
