# Generated by Django 5.0.6 on 2024-09-17 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0030_ordermodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='uname',
        ),
    ]
