# Generated by Django 5.0.6 on 2024-09-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0031_remove_ordermodel_uname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.TextField(null=True),
        ),
    ]
