# Generated by Django 5.0.6 on 2024-09-17 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0035_remove_ordermodel_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='user_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
