# Generated by Django 5.0.6 on 2024-09-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0036_alter_ordermodel_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='product',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
