# Generated by Django 5.0.6 on 2024-09-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0037_alter_ordermodel_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.IntegerField(unique=True)),
                ('gender', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('Role', models.CharField(max_length=100)),
            ],
        ),
    ]
