# Generated by Django 5.0.6 on 2024-09-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0038_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='Address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='Role',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='gender',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
