# Generated by Django 5.0.6 on 2024-09-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0039_alter_manager_address_alter_manager_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.IntegerField(null=True),
        ),
    ]
