# Generated by Django 5.0.6 on 2024-09-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0040_alter_manager_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
