# Generated by Django 5.0.6 on 2024-09-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coffeine', '0042_manager_mag_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
